README.md

Simple options would be more "go like" to be inlined with the calls.
I've also included getting the API key from os.GetEnv rather than people adding it to code to avoid risk of committing an API  key by mistake

fix(doc): Minor update to example code in the README

---

README.md
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go
vpcv1/vpc_v1_integration_test.go
vpcv1/vpc_v1_integration_utils_test.go
vpcv1/vpc_v1_suite_test.go
vpcv1/vpc_v1_test.go

Changes :
-     API version  2021-11-23 -> 2022-01-25
-     vpe sg support
-     `FloatingIPPatchTargetNetworkInterfaceIdentityIntf` -> `FloatingIPTargetPatchIntf`
-     Introduction of `CapturedAt` in `Snapshot`
-     `PublicGatewayIdentityIntf` -> `SubnetPublicGatewayPatchIntf` in `SubnetPatch`

Updated vpc service to use API version 2022-01-25

---

README.md
common/version.go
vpcv1/vpc_v1.go

- Support for HiperSocket network interface for bare metal servers, LinuxONE bare metal servers 
> - `BareMetalServerNetworkInterfaceByHiperSocket`
> - `BareMetalServerNetworkInterfacePrototypeBareMetalServerNetworkInterfaceByHiperSocketPrototype`
- Support for Enterprise account sharing Catalog Images 
> - `CatalogOfferingIdentity`
> - `CatalogOffering` in Image(`ImageCatalogOffering`),  Instance(`InstanceCatalogOffering`), InstancePrototype(`InstanceCatalogOfferingPrototypeIntf`), InstanceTemplate(`InstanceCatalogOfferingPrototypeIntf`), InstanceTemplatePrototype(`InstanceCatalogOfferingPrototypeIntf`) struct
> - `InstancePrototypeInstanceByCatalogOffering`
> - `InstanceTemplateInstanceByCatalogOffering`
> - `InstanceTemplatePrototypeInstanceByCatalogOffering`
- None
- None
- None

feat(2022-09-27): updated the sdk as per the api spec released on 2022-09-27

---

README.md
common/headers.go
common/version.go
vpcv1/vpc_v1.go

- Support for configurable User Agent for the sdk
- Support for `RouteInternetIngress` in `CreateVPCRoutingTableOptions`
- None
- None
- None
Signed-off-by: Ujjwal Kumar <ujjwal.kumar1@ibm.com>
```
Ran 2184 of 2184 Specs in 75.798 seconds
SUCCESS! -- 2184 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (76.63s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 78.462s
```

feat(2022-10-11): updated the sdk as per the api spec released on 2022-10-11

---

README.md
common/version.go
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go
vpcv1/vpc_v1_integration_utils_test.go

```
Ran 2179 of 2179 Specs in 75.484 seconds
SUCCESS! -- 2179 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (76.22s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 77.323s
```
- None
- `VolumeAttachmentPrototypeInstanceContext` is changed to `VolumeAttachmentPrototype`
- `HealthReasons` and `HealthState` in `Volume` struct 
- Addition of warn logs for deprecated features
- None

feat(2022-12-13): updated the sdk as per the api spec released on 2022-12-13

---

README.md
common/version.go
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go
vpcv1/vpc_v1_integration_test.go
vpcv1/vpc_v1_integration_utils_test.go
vpcv1/vpc_v1_suite_test.go

```
Ran 2195 of 2195 Specs in 76.710 seconds
SUCCESS! -- 2195 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (77.62s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 79.511s
```
- datapath in LoadBalancers
- LoadBalancerLoggingDatapathPatch
`LoadBalancerLogging` -> `LoadBalancerLoggingPrototype`
- None
- None
updating of copyright message

feat(2023-01-15): updated the sdk as per the api spec released on 2023-01-15

---

README.md
common/version.go
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go
vpcv1/vpc_v1_integration_test.go
vpcv1/vpc_v1_integration_utils_test.go

-  `Clones` for `Snapshot`
-  `Clones` for `BackupPolicyPlan`
- `IPVersion` in `NetworkACLRulePrototype`
- `TrustedPlatformModule` support for Baremetal servers
- `EnableSecureBoot` support for Baremetal servers
- None
- None
- None
```
Ran 2218 of 2218 Specs in 76.892 seconds
SUCCESS! -- 2218 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (77.74s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 79.616s
```

feat(2023-02-07): updated the sdk as per the api spec released on 2023-02-07

---

README.md
common/version.go
vpcv1/vpc_v1.go

```
Ran 2218 of 2218 Specs in 76.719 seconds
SUCCESS! -- 2218 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (77.56s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 78.710s
```
-  `Protocol`, `ResponseHopLimit` in `InstanceMetadataService`,  `InstanceMetadataServicePatch`, `InstanceMetadataServicePrototype`
- None
- None
- None

feat(2023-02-14): updated the sdk as per the api spec released on 2023-02-14

---

README.md
common/version.go
vpcv1/vpc_v1.go

```
Ran 2223 of 2223 Specs in 77.184 seconds
SUCCESS! -- 2223 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (77.95s)
PASS
ok      github.ibm.com/ibmcloud/vpc-go-sdk/vpcv1        79.029s
```
-  `Priority` in `Route`, `RoutePrototype`, `CreateVPCRouteOptions`, `CreateVPCRoutingTableRouteOptions`
- Support for `InstancePrototypeInstanceByVolume` and `VolumeAttachmentPrototypeInstanceByVolumeContext`
- Support for new filters in `ListVolumesOptions` : `AttachmentState`, `Encryption`, `OperatingSystemFamily`, `OperatingSystemArchitecture`
- Support for `NextHop` , `Priority` in `RoutePatch`
- `OperatingSystemReference` -> `OperatingSystem`
- None
- None

feat(2023-03-21): updated the sdk as per the api spec released on 2023-03-21

---

README.md
common/version.go
vpcv1/vpc_v1.go

```
Ran 2226 of 2226 Specs in 78.407 seconds
SUCCESS! -- 2226 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (79.18s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 79.901s
```
-  `VcpuManufacturer`(`DedicatedHostProfileVcpuManufacturer`, `InstanceProfileVcpuManufacturer`) in `DedicatedHostProfile`, `InstanceProfile`
- Support for `NetworkInterfaceCount`(`InstanceProfileNetworkInterfaceCount`) in `InstanceProfile`
- Support for `Dns`(`LoadBalancerDnsPrototype`) in `LoadBalancer`
- None
- None
- None

feat(2023-03-28): updated the sdk as per the api spec released on 2023-03-28

---

README.md
common/version.go
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go

```
Ran 2257 of 2257 Specs in 79.114 seconds
SUCCESS! -- 2257 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (80.09s)
PASS
ok      github.ibm.com/ibmcloud/vpc-go-sdk/vpcv1        81.311s
```
-  Support for Image export jobs
- None
- None
- None

feat(2023-05-02): updated the sdk as per the api spec released on 2023-05-02

---

README.md
common/version.go
vpcv1/vpc_v1.go
vpcv1/vpc_v1_integration_utils_test.go

```
Ran 2257 of 2257 Specs in 78.547 seconds
SUCCESS! -- 2257 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (79.37s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 82.729s
```
-  Support for TotalCount in `ImageCollection` and `OperatingSystemCollection` 
- `IP` -> `ReservedIPReference` in `VPNGatewayMember` (`PrivateIP`)
- Support for `md5` and `sha1` algorithms in `IkePolicy` and `IpsecPolicy` is discontinued (previously deprecated).
- DH groups `2` and `5` support in `IkePolicy` is discontinued (previously deprecated).
- `triple_des` encryption algorithm support in `IkePolicy` and `IpsecPolicy` is discontinued (previously deprecated).
- None

feat(2023-05-24): updated the sdk as per the api spec released on 2023-05-24

---

README.md
common/version.go
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go

```
Ran 2261 of 2261 Specs in 78.315 seconds
SUCCESS! -- 2261 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (79.18s)
PASS
ok      github.ibm.com/ibmcloud/vpc-go-sdk/vpcv1        80.262s
```
- Support for Backup cross region copies (`RemoteRegionPolicies` in `BackupPolicyPlan`)
- Support for Snapshot cross region copies (`SnapshotPrototypeSnapshotBySourceSnapshot` extension for `SnapshotPrototype`)
- `Copies`(`SnapshotCopiesItem`) and `SourceSnapshot`(`SnapshotSourceSnapshot`) in `Snapshot`
- Support for key type `ed25519` in Keys
- `InstanceGroupsSupported` in `LoadBalancerProfile` and `LoadBalancer`
- `Remote` and `ResourceType` in `ImageReference`
- `ResourceType` in `Image`
in `InstanceTemplate` :
- `InstanceTemplateInstanceByImageInstanceTemplateContext` -> …

feat(spec): updated the sdk as per the api spec released on 2023-07-04

---

README.md
common/version.go
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go

```
Ran 2267 of 2267 Specs in 78.892 seconds
SUCCESS! -- 2267 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (80.68s)
PASS
ok      github.ibm.com/ibmcloud/vpc-go-sdk/vpcv1        82.090s
```
Support for Image Lifecycle Management : 
- Support for `Status` filter in `ListImagesOptions`
- Support for function `DeprecateImage` to deprecate an image using `DeprecateImageOptions`
- Support for function `ObsoleteImage` to obsolete an image using `ObsoleteImageOptions`
- Support for `DeprecationAt` and `ObsolescenceAt` in `ImagePrototype` and  `ImagePatch`
- None
- api version `2023-07-11`
- None

feat(spec): updated the sdk as per the api spec released on 2023-07-11

---

.travis.yml
README.md
common/headers.go
common/headers_test.go
common/version.go
go.mod
go.sum
vpcv1/vpc_v1.go
vpcv1/vpc_v1_examples_test.go

```
Ran 2443 of 2443 Specs in 82.915 seconds
SUCCESS! -- 2443 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (83.83s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 84.998s
```
- None
`ShareSource (Share)->(ShareReference)`
`DeleteVPCDnsResolutionBinding` to return `VpcdnsResolutionBinding` as well
- api version `2023-10-24`
- None

feat(spec): updated the sdk as per the api spec released on 2023-11-22

---

README.md
common/version.go

```
Ran 3341 of 3341 Specs in 92.850 seconds
SUCCESS! -- 3341 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (93.61s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 94.543s
```

feat(spec): updated the sdk as per the api spec released on 2024-07-17

---

.travis.yml
README.md
common/version.go
vpcv1/vpc_v1_examples_test.go

```
Ran 3350 of 3350 Specs in 91.700 seconds
SUCCESS! -- 3350 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (92.50s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 93.591s
```

feat(spec): updated the sdk as per the api spec released on 2024-09-17

---

README.md
common/version.go

```
Ran 3452 of 3452 Specs in 94.699 seconds
SUCCESS! -- 3452 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (95.50s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 96.710s
```
- Support for `DistributeTraffic` for VPN Gateway connection
- None
- api version `2024-10-15`
- None

feat(spec): updated the sdk as per the api spec released on 2024-10-17

---

README.md
common/version.go

```
Ran 3852 of 3852 Specs in 107.337 seconds
SUCCESS! -- 3852 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (108.25s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 109.601s
```

fix(template): correctly unmarshal InstanceTemplate response by type

---

README.md
common/version.go
go.mod
go.sum

```
Ran 3861 of 3861 Specs in 104.418 seconds
SUCCESS! -- 3861 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestVpcV1 (105.33s)
PASS
ok      github.com/IBM/vpc-go-sdk/vpcv1 106.706s
```
* **API Version**: `2025-09-23` → `2025-09-30`
* **New Field Added**: `VolumeBandwidthQosMode` across all instance models
* Values: `pooled`, `weighted`
* Must be supported by instance profile's `volume_bandwidth_qos_modes`
* **New Field**: `VolumeBandwidthQosModes` in `InstanceProfile` struct
* **Instance Model**: Added `VolumeBandwidthQosMode` field
* **InstancePatch**: Added optional field with status restrictions (must be `stopping` or `stopped`)
* **InstancePrototype/Template**: Added optional field with profile validation
* **All Instance Variants**: Updated with `VolumeBandwidthQosMode` …

feat(spec): updated the sdk as per the api spec version 2025-09-30
